# Generated by Django 3.2.23 on 2023-12-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20231215_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, related_name='message_comments', to='message.Comment'),
        ),
    ]
